CREATE OR REPLACE VIEW landing_page AS
SELECT PRODUCT.P_Name, PRODUCT.P_Description, PRODUCT.P_Cost, 
  PRODUCT.P_SaleCost, PRODUCT.P_Weight, PRODUCT.QuantityInStock, 
  LOCATION.StoreAisle AS ProductLocation
FROM PRODUCT
JOIN LOCATION ON LOCATION.L_ID = PRODUCT.L_ID;

