CREATE OR REPLACE VIEW landing_page AS
SELECT PRODUCT.P_Name, PRODUCT.P_Description, PRODUCT.P_Cost, 
  PRODUCT.P_SaleCost, PRODUCT.P_Weight, PRODUCT.QuantityInStock, 
  LOCATION.StoreAisle
FROM PRODUCT
JOIN LOCATION ON LOCATION.L_ID = PRODUCT.L_ID;

CREATE OR REPLACE VIEW search_page AS
SELECT PRODUCT.P_Name, PRODUCT.P_Description, PRODUCT.P_Cost, 
  PRODUCT.P_SaleCost, PRODUCT.P_Weight, PRODUCT.QuantityInStock, 
  LOCATION.StoreAisle, LOCATION.P_Type AS ProductCategory
FROM PRODUCT
JOIN LOCATION ON LOCATION.L_ID = PRODUCT.L_ID;
  
CREATE OR REPLACE VIEW indiv_product_page AS 
SELECT PRODUCT.P_Name, PRODUCT.P_Description, PRODUCT.P_Cost, 
  PRODUCT.P_SaleCost, PRODUCT.P_Weight, PRODUCT.QuantityInStock, 
  LOCATION.StoreAisle
FROM PRODUCT
JOIN LOCATION ON LOCATION.L_ID = PRODUCT.L_ID;
