CREATE TABLE "IT" (
  IT_ID SERIAL NOT NULL,
  IT_FirstName VARCHAR(1024) NOT NULL CHECK (IT_FirstName REGEXP '^[A-Za-z]+$'),
  IT_LastName VARCHAR(1024) NOT NULL CHECK (IT_LastName REGEXP '^[A-Za-z]+$'),
  IT_BirthDate DATE NOT NULL,
  IT_Password VARCHAR(1024) NOT NULL CHECK (IT_Password NOT LIKE  '% %'),
  PRIMARY KEY (IT_ID)
);

CREATE TABLE "MANAGER" (
  M_ID SERIAL NOT NULL,
  M_FirstName VARCHAR(1024) NOT NULL CHECK (M_FirstName REGEXP '^[A-Za-z]+$'),
  M_LastName VARCHAR(1024) NOT NULL CHECK (M_LastName REGEXP '^[A-Za-z]+$'),
  M_BirthDate DATE NOT NULL,
  M_Password VARCHAR(1024) NOT NULL CHECK (M_Password NOT LIKE  '% %'),
  IT_ID INT NOT NULL,
  PRIMARY KEY (M_ID),
  FOREIGN KEY (IT_ID) REFERENCES IT(IT_ID)
);

CREATE TABLE "LOCATION" (
  StoreAisle INT NOT NULL,
  P_Type  VARCHAR(1024) NOT NULL,
  PRIMARY KEY (P_Type)
);

CREATE TABLE "PRODUCT" (
  P_ID SERIAL NOT NULL,
  P_Cost FLOAT NOT NULL,
  P_Weight FLOAT NOT NULL,
  P_SaleCost FLOAT,
  P_Name VARCHAR(1024)  NOT NULL,
  P_Description VARCHAR(1024)  NOT NULL,
  QuantityInStock INT NOT NULL,
  M_ID INT NOT NULL,
  P_Type INT NOT NULL,
  PRIMARY KEY (P_ID),
  FOREIGN KEY (M_ID) REFERENCES MANAGER(M_ID),
  FOREIGN KEY (P_Type) REFERENCES LOCATION(P_Type)
);

CREATE TABLE "STOCKER" (
  S_ID SERIAL NOT NULL,
  S_FirstName VARCHAR(1024) NOT NULL CHECK (S_FirstName REGEXP '^[A-Za-z]+$'),
  S_LastName VARCHAR(1024) NOT NULL CHECK (S_LastName REGEXP '^[A-Za-z]+$'),
  S_BirthDate DATE NOT NULL,
  S_Password VARCHAR(1024)  NOT NULL CHECK (S_Password NOT LIKE  '% %'),
  M_ID INT NOT NULL,
  IT_ID INT NOT NULL,
  PRIMARY KEY (S_ID),
  FOREIGN KEY (M_ID) REFERENCES MANAGER(M_ID),
  FOREIGN KEY (IT_ID) REFERENCES IT(IT_ID)
);

CREATE TABLE "STOCKS" (
  S_ID INT NOT NULL,
  P_ID INT NOT NULL,
  PRIMARY KEY (S_ID, P_ID),
  FOREIGN KEY (S_ID) REFERENCES STOCKER(S_ID),
  FOREIGN KEY (P_ID) REFERENCES PRODUCT(P_ID)
);
