DROP TABLE IF EXISTS PRODUCT;
DROP TABLE IF EXISTS STOCKER;
DROP TABLE IF EXISTS MANAGER;
DROP TABLE IF EXISTS IT;
DROP TABLE IF EXISTS LOCATION;

CREATE TABLE IT (
  IT_ID SERIAL,
  IT_FirstName VARCHAR(50) NOT NULL CHECK (IT_FirstName REGEXP '^[A-Za-z]+$'),
  IT_LastName VARCHAR(50) NOT NULL CHECK (IT_LastName REGEXP '^[A-Za-z]+$'),
  IT_BirthDate DATE NOT NULL,
  IT_Password VARCHAR(255) NOT NULL,
  PRIMARY KEY (IT_ID)
);

CREATE TABLE MANAGER (
  M_ID SERIAL,
  M_FirstName VARCHAR(50) NOT NULL CHECK (M_FirstName REGEXP '^[A-Za-z]+$'),
  M_LastName VARCHAR(50) NOT NULL CHECK (M_LastName REGEXP '^[A-Za-z]+$'),
  M_BirthDate DATE NOT NULL,
  M_Password VARCHAR(255) NOT NULL,
  IT_ID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (M_ID),
  FOREIGN KEY (IT_ID) REFERENCES IT(IT_ID)
);

CREATE TABLE LOCATION (
  L_ID SERIAL,
  StoreAisle INT NOT NULL CHECK (StoreAisle BETWEEN 10 AND 99),
  P_Type VARCHAR(50) NOT NULL,
  PRIMARY KEY (L_ID),
  UNIQUE (P_Type)
);

CREATE TABLE PRODUCT (
  P_ID SERIAL,
  P_Cost DECIMAL (10,2) NOT NULL CHECK (P_Cost > 0),
  P_Weight DECIMAL(4,2) NOT NULL CHECK (P_Weight > 0),
  P_SaleCost DECIMAL (10,2) CHECK (P_SaleCost > 0), 
  P_Name VARCHAR(50) NOT NULL,
  P_Description VARCHAR(300) NOT NULL,
  QuantityInStock INT NOT NULL,
  M_ID BIGINT UNSIGNED NOT NULL,
  L_ID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (P_ID),
  FOREIGN KEY (M_ID) REFERENCES MANAGER(M_ID),
  FOREIGN KEY (L_ID) REFERENCES LOCATION(L_ID)
);

CREATE TABLE STOCKER (
  S_ID SERIAL,
  S_FirstName VARCHAR(50) NOT NULL CHECK (S_FirstName REGEXP '^[A-Za-z]+$'),
  S_LastName VARCHAR(50) NOT NULL CHECK (S_LastName REGEXP '^[A-Za-z]+$'),
  S_BirthDate DATE NOT NULL,
  S_Password VARCHAR(255) NOT NULL,
  M_ID BIGINT UNSIGNED NOT NULL,
  IT_ID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (S_ID),
  FOREIGN KEY (M_ID) REFERENCES MANAGER(M_ID),
  FOREIGN KEY (IT_ID) REFERENCES IT(IT_ID)
);

CREATE TABLE STOCKS (
  S_ID BIGINT UNSIGNED NOT NULL,
  P_ID BIGINT UNSIGNED NOT NULL,
  PRIMARY KEY (S_ID, P_ID),
  FOREIGN KEY (S_ID) REFERENCES STOCKER(S_ID),
  FOREIGN KEY (P_ID) REFERENCES PRODUCT(P_ID)
);

ALTER TABLE IT AUTO_INCREMENT = 100000;
ALTER TABLE MANAGER AUTO_INCREMENT = 200000;
ALTER TABLE STOCKER AUTO_INCREMENT = 300000;
ALTER TABLE LOCATION AUTO_INCREMENT = 400000;
ALTER TABLE PRODUCT AUTO_INCREMENT = 1000000;
